#!/bin/bash

set -e -x

export GEM_HOME=$HOME/gems
mkdir $GEM_HOME

export PATH=$GEM_HOME/bin:$PATH

apt-get -y install ca-certificates

cd atomy
bundle install

# smoke test
bundle exec atomy kernel/atomy.ay

# run tests
bundle exec rspec
