<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>bundleUUID</key>
    <string>923BC912-B678-4254-9039-B99C3B210347</string>
    <key>fileTypes</key>
    <array>
        <string>ay</string>
    </array>
    <key>foldingStartMarker</key>
    <string>^\s*[_A-z0-9]+@.+$</string>
    <key>foldingStopMarker</key>
    <string>^.*(\])[A-z ]*\.$</string>
    <key>name</key>
    <string>Atomy</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(do|if|then|else|while|until|loop|when|unless|restart|with-restarts|bind|return|break|next|labels|super|yield|raise|rescue|ensuring|match|condition|otherwise|catch|throw|exit)(?![\p{L}\d!@#%&amp;*\-./\?\p{S}])</string>
            <key>name</key>
            <string>keyword.control.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(error|warning|signal|namespace|using|import|in-namespace)(?![\p{L}\d!@#%&amp;*\-./\?\p{S}])</string>
            <key>name</key>
            <string>support.function.kernel.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(macro|operator)(?![\p{L}\d!@#%&amp;*\-./\?\p{S}])</string>
            <key>name</key>
            <string>keyword.other.reserved.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(self|me)(?![\p{L}\d!@#%&amp;*\-./\?\p{S}])</string>
            <key>name</key>
            <string>variable.language.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>['`][\p{Ll}_][\p{L}\d!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>string.quoted.other.expression.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>~[\p{Ll}_][\p{L}\d!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>string.interpolated.expression.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>~\*[\p{Ll}_][\p{L}\d!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>string.interpolated.expression.atomy</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>['`]\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>string.quoted.other.expression.atomy</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_parens</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>~\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>string.interpolated.expression.atomy</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_parens</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>~\*\(</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>string.interpolated.expression.atomy</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_parens</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>include</key>
            <string>#string</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#line_comment</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#block_comment</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(&amp;&amp;|\|\||!)(?![\p{L}\d!@#%&amp;*\-./\?\p{S}])</string>
            <key>name</key>
            <string>keyword.operator.logical.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(true|false|nil)(?![\p{L}\d!@#%&amp;*\-./\?\p{S}])</string>
            <key>name</key>
            <string>constant.language.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(?i:(0x\h*))</string>
            <key>name</key>
            <string>constant.numeric.integer.hexadecimal.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(?i:(0o[0-7]*))</string>
            <key>name</key>
            <string>constant.numeric.integer.octal.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
            <key>name</key>
            <string>constant.numeric.float.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;=[^0-9a-zA-Z_])(?i:(\.\d+(e[\-\+]?\d+)?))</string>
            <key>name</key>
            <string>constant.numeric.float.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(?i:(\d+e[\-\+]?\d+))</string>
            <key>name</key>
            <string>constant.numeric.float.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])([\-\+]?\d+/[\-\+]?\d+)</string>
            <key>name</key>
            <string>constant.numeric.rational.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])([\-\+]?\d+)</string>
            <key>name</key>
            <string>constant.numeric.integer.decimal.atomy</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.constant.atomy</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(#)[\p{Ll}_][\p{L}\d!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>constant.other.symbol.atomy</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.variable.atomy</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(@)[a-z_][[:alnum:]_!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>variable.other.readwrite.instance.atomy</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.variable.atomy</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(@@)[a-z_][[:alnum:]_!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>variable.other.readwrite.class.atomy</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.variable.atomy</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])($)[a-z_][[:alnum:]_!@#%&amp;*\-./\?\p{S}]*</string>
            <key>name</key>
            <string>variable.other.readwrite.global.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;![\p{L}\d!@#%&amp;*\-./\?\p{S}])(?!--|`|~)([\p{S}!@#%&amp;*\-\\:.\/\?]+)</string>
            <key>name</key>
            <string>keyword.operator.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[A-Z_][[:alnum:]_]*</string>
            <key>name</key>
            <string>variable.other.atomy, entity.name.class</string>
        </dict>
        <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.object.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>punctuation.section.scope.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[|\]</string>
            <key>name</key>
            <string>punctuation.section.array.atomy</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>punctuation.section.function.atomy</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>nest_parens</key>
        <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nest_parens</string>
                </dict>

                <dict>
                    <key>include</key>
                    <string>$self</string>
                </dict>
            </array>
        </dict>
        <key>line_comment</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.atomy</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(--).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-dash.atomy</string>
        </dict>
        <key>block_comment</key>
        <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>\{-</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.atomy</string>
                </dict>
            </dict>
            <key>end</key>
            <string>-\}</string>
            <key>name</key>
            <string>comment.block.atomy</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#block_comment</string>
                </dict>
            </array>
        </dict>
        <key>string</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.atomy</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.atomy</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.atomy</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\\"'\&amp;])</string>
                    <key>name</key>
                    <string>constant.character.escape.atomy</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\\o[0-7]+|\\x[0-9A-Fa-f]+|\\[0-9]+</string>
                    <key>name</key>
                    <string>constant.character.escape.octal.atomy</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\^[A-Z@\[\]\\\^_]</string>
                    <key>name</key>
                    <string>constant.character.escape.control.atomy</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.atomy</string>
    <key>uuid</key>
    <string>4CB79AE8-8C19-4410-BB2F-EA0583F39D13</string>
</dict>
</plist>